name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures the full history for Nx commands
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'  # Caches npm dependencies for faster future builds
      - run: npm ci --force  # Install dependencies
      - run: npx nx --version  # Verifies that Nx is installed
      - run: npx nx run task-management:build  # Build the specific task-management project

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASK_BUDDY_FED16 }}
          channelId: live  # Adjust if you want a different channel for previews
          projectId: task-buddy-fed16  # Your Firebase project ID
